# custom config for aki setup
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$(go env GOPATH)/bin
export XDG_CONFIG_HOME=/home/aki/.config

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


alias inflate='ruby -r zlib -e "STDOUT.write Zlib::Inflate.inflate(STDIN.read)"'

alias tmls='tmux ls'
alias tmk='tmux kill-server'

function tma {
    name=$1
    result=${PWD##*/}          # to assign to a variable
    result=${result:-/}        # to correct for the case where PWD=/
    tmux new -A -s $name -n $result
}

alias dev='tma dev'
alias stg='tma stg'
alias prd='tma prd'

alias cat='batcat'
